replicaCount: 1

image:
  repository: almogbcr/simpleflaskapp
  tag: "d49f07c"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

container:
  port: 8000

autoscaling:
  enabled: false

serviceAccount:
  create: false
  name: ""

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: true
  host: myapp-prod.local    
