replicaCount: 1

image:
  repository: almogbcr/simpleflaskapp
  tag: "cd69678"
  pullPolicy: Always  

service:
  type: NodePort
  port: 80
  nodePort: 30008   

container:
  port: 8000

autoscaling:
  enabled: false

serviceAccount:
  create: false
  name: ""

resources: {}
