replicaCount: 1

image:
  repository: almogbcr/simpleflaskapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80


container:
  port: 8000

autoscaling:
  enabled: false

serviceAccount:
  create: false
  name: ""

resources: {}